Flutter provider
Robert-Scub/formation-flutter pull request #100
Opened 2023-04-12 10:59 UTC by karim-lamtara

2023-04-12 11:31 UTC, ddeshayes commented on demo/provider/README.md
> +On a vu dans le cours Statelss/stateful que l'etat d'un statefulWidget peut etre manipulé depuis le widget lui meme
stateless

2023-04-12 12:44 UTC, ddeshayes approved these changes

2023-04-13 07:45 UTC, alexandre-scub requested changes

2023-04-13 07:45 UTC, alexandre-scub commented on demo/provider/README.md
> +Vous vous etes certainement demandés comment faire pour changer l'etat d'un widget A depuis un widget B sachant qu'ils n'ont aucun
c'est un détail mais ajoute le ^sur le e êtes

2023-04-13 07:45 UTC, alexandre-scub commented on demo/provider/README.md
> +    Le paramètre booléen listen et facultatif, sa valeur par defaut est true, mettre ce paramètre a false permets d'eviter
*est au lieu de et

2023-04-18 08:29 UTC, closed without merging