Console-class
Robert-Scub/formation-flutter pull request #80
Opened 2023-04-04 08:57 UTC by Loghann-Mussard

2023-04-04 11:54 UTC, ddeshayes approved these changes

2023-04-05 10:07 UTC, alexandre-scub requested changes

2023-04-05 10:07 UTC, alexandre-scub commented on console/class_lesson/README.md
> +### NOTE IMPORTANTE: A chaque cours, il faut isoler ceux ci et mettre la methode main et non main + un chiffre comme montré de ce cours
Je pense que tu as oublié de supprimer ce commentaire dans le Markdown. Supprime le et je valide ta PR :)

2023-04-05 14:12 UTC, alexandre-scub approved these changes

2023-04-05 14:12 UTC, merged