Demo statless statful
Robert-Scub/formation-flutter pull request #90
Opened 2023-04-06 08:30 UTC by karim-lamtara

2023-04-06 13:18 UTC, ddeshayes commented on demo/stateless_stateful/README.md
> +### Widge sans etat
widget

2023-04-06 13:21 UTC, ddeshayes commented on demo/stateless_stateful/README.md
> +    class RandomWordPage extends StatefulWidget {
utilise les backtick (``` code...  ```) recommende par Robert

2023-04-12 12:43 UTC, Loghann-Mussard commented on demo/stateless_stateful/README.md
> +Dans cette section, je vais détailler la création un widget avec état personnalisé. notre wigdet affichera un mot aléatoire
remplace 'notre widget' par 'Notre widget' comme il y a un point juste avant.

2023-04-12 12:44 UTC, Loghann-Mussard commented on demo/stateless_stateful/README.md
> +    1: Une sous-classe de StatefulWidgetdéfinit le widget.
il manque un espace entre StatefulWidget et définit

2023-04-12 12:45 UTC, Loghann-Mussard commented on demo/stateless_stateful/README.md
> +    2: Une sous-classe de Statequi contient l'état de ce widget et définit la build()méthode du widget.
il manque un espace entre 'State' et 'qui'

2023-04-12 12:48 UTC, Loghann-Mussard commented on demo/stateless_stateful/README.md
>  Afficher un mot aléatoire depuis une liste et l'actualiser grace a un button.
grâce et non grace

2023-04-12 12:50 UTC, Loghann-Mussard commented on demo/stateless_stateful/lib/main.dart
> +  /// List de mots
Liste et non List qui est en anglais...je sais que c'est l'habitude ^^

2023-04-12 12:52 UTC, Loghann-Mussard requested changes
keep going

2023-04-12 13:00 UTC, Loghann-Mussard approved these changes
Excellent

2023-04-12 13:02 UTC, merged