Console future
Robert-Scub/formation-flutter pull request #96
Opened 2023-04-07 07:24 UTC by ddeshayes

2023-04-07 08:48 UTC, Loghann-Mussard commented on console/future/isolate/bin/future.dart
> +  // appart si vous utiliser le compute de flutter qui gère tout ça pour vous
'appart' n'existe pas. Remplace le par 'sauf si'

2023-04-07 08:49 UTC, Loghann-Mussard commented on console/future/isolate/bin/future.dart
> +  // N'oubliez pas  de kill l'isolate afin d'évite tout fuite mémoire ou performance
il y a 2 espaces entre 'pas' et 'de'. Ensuite, je ne sais pas si 'kill' est un bon terme à utiliser dans une appli pro...

2023-04-07 08:56 UTC, Loghann-Mussard requested changes
petits changements à faire mais tu es sur la bonne voie

2023-04-07 08:58 UTC, ddeshayes commented on console/future/isolate/bin/future.dart
> +  // N'oubliez pas  de kill l'isolate afin d'évite tout fuite mémoire ou performance
c'est le terme => on kill un process , dans l'isolate il y a même une méthode qui est Isolate.kill()

2023-04-11 08:10 UTC, Loghann-Mussard approved these changes
Great

2023-04-12 07:45 UTC, alexandre-scub approved these changes

2023-04-12 07:45 UTC, merged